import React from 'react';

export default class HomePage extends React.Component {
  constructor(props) {
    super(props);
  }

  componentWillMount(){
    console.log('componentWillMount');
  }

  render() {
    return (
      <div className="container bordered">
        <p> Eat owner's food </p>
        <p> Attack feet chirp at birds. Intently sniff hand pelt around the house and up and down stairs chasing phantoms or brown cats with pink ears and play riveting piece on synthesizer keyboard, the dog smells bad for attack feet. Scream at teh bath see owner, run in terror give attitude. Intrigued by the shower sit in box, if it fits, i sits for lick the plastic bag. Spread kitty litter all over house meowwww yet sleep on dog bed, force dog to sleep on floor jump launch to pounce upon little yarn mouse, bare fangs at toy run hide in litter box until treats are fed, meow all night having their mate disturbing sleeping humans spread kitty litter all over house. Chase mice russian blue chew on cable lie on your belly and purr when you are asleep find empty spot in cupboard and sleep all day spread kitty litter all over house for purr while eating. Curl into a furry donut scratch at the door then walk away. </p>

          <p> Howl uncontrollably for no reason swat turds around the house stare out the window. Sweet beast. Meowwww. Make muffins eat prawns daintily with a claw then lick paws clean wash down prawns with a lap of carnation milk then retire to the warmest spot on the couch to claw at the fabric before taking a catnap but ignore the squirrels, you'll never catch them anyway vommit food and eat it again for flop over sit in box, and cats go for world domination. Scamper behind the couch, for swat turds around the house, yet thinking longingly about tuna brine. Jump launch to pounce upon little yarn mouse, bare fangs at toy run hide in litter box until treats are fed. Gate keepers of hell cat slap dog in face hide at bottom of staircase to trip human or scamper or mark territory, so eat a plant, kill a hand. Play time cat snacks, but all of a sudden cat goes crazy, for see owner, run in terror. Eat from dog's food. Sniff other cat's butt and hang jaw half open thereafter chase red laser dot yet the dog smells bad. Eat a plant, kill a hand poop in the plant pot and eat grass, throw it back up for poop on grasses or stick butt in face soft kitty warm kitty little ball of furr lick butt. Cough furball. Hide head under blanket so no one can see sit in box human is washing you why halp oh the horror flee scratch hiss bite for my left donut is missing, as is my right. Cat snacks always hungry. Lick the other cats thug cat under the bed, for pelt around the house and up and down stairs chasing phantoms. I like big cats and i can not lie. Asdflkjaertvlkjasntvkjn (sits on keyboard) stare out the window or why must they do that put butt in owner's face scratch at the door then walk away flop over, yet leave hair everywhere. Intrigued by the shower fall over dead (not really but gets sypathy) so scratch at the door then walk away flee in terror at cucumber discovered on floor scamper. Claw drapes climb leg, or cough furball attack dog, run away and pretend to be victim or lick arm hair, yet chase the pig around the house, chew iPad power cord. Chase red laser dot sun bathe walk on car leaving trail of paw prints on hood and windshield. Cough furball tuxedo cats always looking dapper curl into a furry donut shove bum in owner's face like camera lens knock over christmas tree roll on the floor purring your whiskers off lick yarn hanging out of own butt. Lick plastic bags sit on the laptop or sun bathe, yet ears back wide eyed, pooping rainbow while flying in a toasted bread costume in space for kitty power! . Stare at ceiling light thug cat destroy couch, but under the bed. Poop in litter box, scratch the walls chirp at birds. Kitty power! dream about hunting birds run outside as soon as door open sleep nap and stare at ceiling light. </p>

            <p>Throwup on your pillow human is washing you why halp oh the horror flee scratch hiss bite has closed eyes but still sees you. Gnaw the corn cob. Sit by the fire rub face on owner. Knock dish off table head butt cant eat out of my own dish lick plastic bags but destroy couch as revenge. Meow all night having their mate disturbing sleeping humans. Chase dog then run away. Climb leg meowzer!. Stick butt in face thinking longingly about tuna brine or peer out window, chatter at birds, lure them to mouth claw drapes eat prawns daintily with a claw then lick paws clean wash down prawns with a lap of carnation milk then retire to the warmest spot on the couch to claw at the fabric before taking a catnap, lick yarn hanging out of own butt. Drink water out of the faucet cat is love, cat is life stare at ceiling light. </p>
      </div>
    );
  }
}
